DECLARE @sql VARCHAR(4096)
DECLARE @date VARCHAR(14)
	
SET @date = DATEADD(M, -6, CONVERT(DATE, CONVERT(VARCHAR(6), GETDATE(),112) + '01')) 
	

IF EXISTS (SELECT * FROM TEMPDB.SYS.ALL_OBJECTS WHERE NAME LIKE '%#TMP%') 
DROP TABLE #TMP 

SELECT YEAR (CREATE_DATE)AS YEAR,
 MONTH(CREATE_DATE)AS MONTH ,
 COUNT (*) AS NBR_LIGNES 
 INTO #TMP 
 FROM EVENT WHERE CREATE_DATE < DATEADD(M, -6, CONVERT(DATE, CONVERT(VARCHAR(6), GETDATE(),112) + '01')) 
GROUP BY YEAR (CREATE_DATE), MONTH(CREATE_DATE)
ORDER BY YEAR (CREATE_DATE)DESC , MONTH(CREATE_DATE)DESC 

SELECT 'DELETE FROM EVENT WHERE YEAR (CREATE_DATE) = '+CAST ([YEAR] AS VARCHAR)+' AND MONTH (CREATE_DATE) = '+CAST ([MONTH] AS VARCHAR)+' ; ' + CHAR(13) + '' FROM #TMP 

set @sql= 'DELETE FROM EVENT WHERE YEAR (CREATE_DATE) = '''+cast (YEAR (@date) as varchar)+''' AND MONTH (CREATE_DATE) = '''+cast (MONTH (@date) as varchar)+''' ; ''' + CHAR(13) + ''''  

print @sql