----------OUVRIR BDD

 ALTER DATABASE [master] SET ONLINE  
 GO  
 ALTER DATABASE [tempdb] SET ONLINE  
 GO  
 ALTER DATABASE [model] SET ONLINE  
 GO  
 ALTER DATABASE [msdb] SET ONLINE  
 GO  
 ALTER DATABASE [ReportServer] SET ONLINE  
 GO  
 ALTER DATABASE [ReportServerTempDB] SET ONLINE  
 GO  
 --ALTER DATABASE [AdminSQL] SET ONLINE  
 --GO  
 ALTER DATABASE [DSM] SET ONLINE  
 GO  
 ALTER DATABASE [OperationsManager] SET ONLINE  
 GO  
 ALTER DATABASE [KAV] SET ONLINE  
 GO  
 ALTER DATABASE [KAV2008] SET ONLINE  
 GO  
 ALTER DATABASE [EnterpriseVaultDirectory] SET ONLINE  
 GO  
 ALTER DATABASE [VIM_UMDB] SET ONLINE  
 GO  
 ALTER DATABASE [VIM_VCDB] SET ONLINE  
 GO  
 ALTER DATABASE [EnterpriseVaultMonitoring] SET ONLINE  
 GO  
 ALTER DATABASE [EVVSGVSGVILFR01_1_1] SET ONLINE  
 GO  
 ALTER DATABASE [EVVSFSAQUICKVILFR_2] SET ONLINE  
 GO  
 ALTER DATABASE [EVVSMBAQUICKVILFR_1] SET ONLINE  
 GO  
 ALTER DATABASE [LcsCDR] SET ONLINE  
 GO  
 ALTER DATABASE [QoEMetrics] SET ONLINE  
 GO  
 ALTER DATABASE [FenMessaging] SET ONLINE  
 GO  
 ALTER DATABASE [wbsn-data-security] SET ONLINE  
 GO  
 ALTER DATABASE [wbsn-data-security-temp-archive] SET ONLINE  
 GO  
 ALTER DATABASE [xcalibur_faf3c5d] SET ONLINE  
 GO  
 ALTER DATABASE [FIMSynchronizationService] SET ONLINE  
 GO  
 ALTER DATABASE [FIMService] SET ONLINE  
 GO  
 ALTER DATABASE [xcalibur_faf3c5d1] SET ONLINE  
 GO  
 ALTER DATABASE [WorkspaceManager] SET ONLINE  
 GO  
 ALTER DATABASE [SNOWDB] SET ONLINE  
 GO  
 ALTER DATABASE [SnowLicenseManager] SET ONLINE  
 GO  
 ALTER DATABASE [OperationsManagerDW] SET ONLINE  
 GO  
 ALTER DATABASE [CM_FR1] SET ONLINE  
 GO  
 ALTER DATABASE [ReportServerSCCM] SET ONLINE  
 GO  
 ALTER DATABASE [ReportServerSCCMTempDB] SET ONLINE  
 GO  
 ALTER DATABASE [KAVBE] SET ONLINE  
 GO  
 
 
  ALTER DATABASE [master] SET MULTI_USER  
  GO  
 ALTER DATABASE [tempdb] SET MULTI_USER  
 GO  
 ALTER DATABASE [model] SET MULTI_USER  
 GO  
 ALTER DATABASE [msdb] SET MULTI_USER  
 GO  
 ALTER DATABASE [ReportServer] SET MULTI_USER  
 GO  
 ALTER DATABASE [ReportServerTempDB] SET MULTI_USER  
 GO  
 --ALTER DATABASE [AdminSQL] SET MULTI_USER  
 --GO  
 ALTER DATABASE [DSM] SET MULTI_USER  

 GO  
 ALTER DATABASE [OperationsManager] SET MULTI_USER  
 GO  
 ALTER DATABASE [KAV] SET MULTI_USER  
 GO  
 ALTER DATABASE [KAV2008] SET MULTI_USER  
 GO  
 ALTER DATABASE [EnterpriseVaultDirectory] SET MULTI_USER  
 GO  
 ALTER DATABASE [VIM_UMDB] SET MULTI_USER  
 GO  
 ALTER DATABASE [VIM_VCDB] SET MULTI_USER  
 GO  
 ALTER DATABASE [EnterpriseVaultMonitoring] SET MULTI_USER  
 GO  
 ALTER DATABASE [EVVSGVSGVILFR01_1_1] SET MULTI_USER  
 GO  
 ALTER DATABASE [EVVSFSAQUICKVILFR_2] SET MULTI_USER  
 GO  
 ALTER DATABASE [EVVSMBAQUICKVILFR_1] SET MULTI_USER  
 GO  
 ALTER DATABASE [LcsCDR] SET MULTI_USER  
 GO  
 ALTER DATABASE [QoEMetrics] SET MULTI_USER  
 GO  
 ALTER DATABASE [FenMessaging] SET MULTI_USER  
 GO  
 ALTER DATABASE [wbsn-data-security] SET MULTI_USER  
 GO  
 ALTER DATABASE [wbsn-data-security-temp-archive] SET MULTI_USER  
 GO  
 ALTER DATABASE [xcalibur_faf3c5d] SET MULTI_USER  
 GO  
 ALTER DATABASE [FIMSynchronizationService] SET MULTI_USER 
 GO  
 ALTER DATABASE [FIMService] SET MULTI_USER  
 GO  
 ALTER DATABASE [xcalibur_faf3c5d1] SET MULTI_USER  
 GO  
 ALTER DATABASE [WorkspaceManager] SET MULTI_USER  
 GO  
 ALTER DATABASE [SNOWDB] SET MULTI_USER  
 GO  
 ALTER DATABASE [SnowLicenseManager] SET MULTI_USER  
 GO  
 ALTER DATABASE [OperationsManagerDW] SET MULTI_USER  
 GO  
 ALTER DATABASE [CM_FR1] SET MULTI_USER  
 GO  
 ALTER DATABASE [ReportServerSCCM] SET MULTI_USER  
 GO  
 ALTER DATABASE [ReportServerSCCMTempDB] SET MULTI_USER  
 GO  
 ALTER DATABASE [KAVBE] SET MULTI_USER  
 GO  