-----------ARRET DES BDD 

 ALTER DATABASE master SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE tempdb SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE model SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE msdb SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE ReportServer SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE ReportServerTempDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 --ALTER DATABASE AdminSQL SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 --GO  
 ALTER DATABASE DSM SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE OperationsManager SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE KAV SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE KAV2008 SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE EnterpriseVaultDirectory SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE VIM_UMDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE VIM_VCDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE EnterpriseVaultMonitoring SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE EVVSGVSGVILFR01_1_1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE EVVSFSAQUICKVILFR_2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE EVVSMBAQUICKVILFR_1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE LcsCDR SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE QoEMetrics SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE FenMessaging SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE [wbsn-data-security] SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE [wbsn-data-security-temp-archive] SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE xcalibur_faf3c5d SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE FIMSynchronizationService SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE FIMService SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE xcalibur_faf3c5d1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE WorkspaceManager SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE SNOWDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE SnowLicenseManager SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE OperationsManagerDW SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE CM_FR1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE 
 GO  
 ALTER DATABASE ReportServerSCCM SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE ReportServerSCCMTempDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
 ALTER DATABASE KAVBE SET SINGLE_USER WITH ROLLBACK IMMEDIATE  
 GO  
  ALTER DATABASE master SET OFFLINE  
  GO  
 ALTER DATABASE tempdb SET OFFLINE  
 GO  
 ALTER DATABASE model SET OFFLINE  
 GO  
 ALTER DATABASE msdb SET OFFLINE  
 GO  
 ALTER DATABASE ReportServer SET OFFLINE  
 GO  
 ALTER DATABASE ReportServerTempDB SET OFFLINE  
 GO  
 --ALTER DATABASE AdminSQL SET OFFLINE  
 --GO  
 ALTER DATABASE DSM SET OFFLINE  
 GO  
 ALTER DATABASE OperationsManager SET OFFLINE  
 GO  
 ALTER DATABASE KAV SET OFFLINE  
 GO  
 ALTER DATABASE KAV2008 SET OFFLINE  
 GO  
 ALTER DATABASE EnterpriseVaultDirectory SET OFFLINE  
 GO  
 ALTER DATABASE VIM_UMDB SET OFFLINE  
 GO  
 ALTER DATABASE VIM_VCDB SET OFFLINE  
 GO  
 ALTER DATABASE EnterpriseVaultMonitoring SET OFFLINE  
 GO  
 ALTER DATABASE EVVSGVSGVILFR01_1_1 SET OFFLINE  
 GO  
 ALTER DATABASE EVVSFSAQUICKVILFR_2 SET OFFLINE  
 GO  
 ALTER DATABASE EVVSMBAQUICKVILFR_1 SET OFFLINE  
 GO  
 ALTER DATABASE LcsCDR SET OFFLINE  
 GO  
 ALTER DATABASE QoEMetrics SET OFFLINE  
 GO  
 ALTER DATABASE FenMessaging SET OFFLINE  
 GO  
 ALTER DATABASE [wbsn-data-security] SET OFFLINE  
 GO  
 ALTER DATABASE [wbsn-data-security-temp-archive] SET OFFLINE  
 GO  
 ALTER DATABASE xcalibur_faf3c5d SET OFFLINE  
 GO  
 ALTER DATABASE FIMSynchronizationService SET OFFLINE  
 GO  
 ALTER DATABASE FIMService SET OFFLINE  
 GO  
 ALTER DATABASE xcalibur_faf3c5d1 SET OFFLINE  
 GO  
 ALTER DATABASE WorkspaceManager SET OFFLINE  
 GO  
 ALTER DATABASE SNOWDB SET OFFLINE  
 GO  
 ALTER DATABASE SnowLicenseManager SET OFFLINE  
 GO  
 ALTER DATABASE OperationsManagerDW SET OFFLINE  
 GO  
 ALTER DATABASE CM_FR1 SET OFFLINE  
 GO  
 ALTER DATABASE ReportServerSCCM SET OFFLINE  
 GO  
 ALTER DATABASE ReportServerSCCMTempDB SET OFFLINE  
 GO  
 ALTER DATABASE KAVBE SET OFFLINE  
 GO  