BACKUP DATABASE [AXSCMPROD] 
TO  DISK = N'D:\AXSCMPROD1.bak',
  DISK = N'E:\AXSCMPROD2.bak',
  DISK = N'G:\AXSCMPROD3.bak',
  DISK = N'G:\AXSCMPROD4.bak'
WITH NOFORMAT, NOINIT,  NAME = N'AXSCMPROD-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 1
GO


BACKUP LOG [AXSCMPROD] 
TO  DISK = N'\\vilfraxsqlvm\p$\AXSCMPROD_Log2.trn' 
WITH  NOFORMAT, NOINIT,  NAME = N'AXSCMPROD-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 1
GO