
SET STATISTICS IO ON
SET STATISTICS TIME ON 

SELECT *
FROM ODS..ODS_PIQUICK_Ventes Ventes
WHERE Ventes.CommercialDate='2015-04-24'
AND Ventes.RestaurantUniqueId = 20040720


SET STATISTICS IO OFF
SET STATISTICS TIME OFF