USE [master]
RESTORE DATABASE [AXSCMPROD] 
FROM  DISK = N'P:\AXSCMPROD1.bak',
  DISK = N'P:\AXSCMPROD2.bak',
  DISK = N'P:\AXSCMPROD3.bak',
  DISK = N'P:\AXSCMPROD4.bak'
	  WITH  FILE = 1,  
MOVE N'AXSCMPROD_Data' TO N'D:\DATA\AXSCMPROD_Data.MDF', 
MOVE N'AXSCMPROD_Data2' TO N'D:\DATA\AXSCMPROD_Data2.NDF',  
MOVE N'AXSCMPROD_Log' TO N'L:\LOG\AXSCMPROD_Log.LDF',  
MOVE N'AXSCMPROD_Log2' TO N'L:\LOG\AXSCMPROD_Log2.ldf', 
NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 1
GO

RESTORE LOG  [AXSCMPROD] 
FROM  DISK = N'\\vilfraxsqlvm\p$\AXSCMPROD_Log2.trn' 
WITH  NORECOVERY

