DECLARE @restau varchar(250)

DECLARE Rest_Cursor CURSOR FOR  

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT distinct (RestaurantUniqueID)
  FROM [SID_PRD].[ODS].[SHP_BK_SHAREPOINT_RESTAURANT]
where RestaurantUniqueID like '8004%'
order by RestaurantUniqueID  
OPEN Rest_Cursor  
FETCH NEXT FROM Rest_Cursor INTO @restau 
WHILE @@FETCH_STATUS = 0
    BEGIN 
	PRINT @restau
	FETCH  NEXT FROM Rest_Cursor INTO @restau 
--OPEN Rest_Cursor
--FETCH NEXT FROM Rest_Cursor INTO @restau 
--WHILE @@FETCH_STATUS = 0  
--   BEGIN  
--      FETCH NEXT FROM Rest_Cursor;  c
--INSERT INTO SDBKQ067.AdminSQL.[dbo].[TICKET_UNIFIE]
--           ([RestaurantCode]
--           ,[RestaurantUniqueID]
--           ,[InvoiceID]
--           ,[InvoiceTransactionID]
--           ,[CommercialDate]
--           ,[CodePLU]
--           ,[RevenueDate]
--           ,[TITT_TaxeID]
--           ,[Pays_seq]
--           ,[CommercialMonth]
--           ,[TI_OpenDate]
--           ,[TI_CloseDate]
--           ,[Periode]
--           ,[CAT_RevenueCenterID]
--           ,[InvoiceNumber]
--           ,[FlagDeleted]
--           ,[FlagPosted]
--           ,[FlagTraining]
--           ,[SID_PRODUCT]
--           ,[ParentInvoiceTransactionID]
--           ,[InCombo]
--           ,[Quantity]
--           ,[UnitPrice]
--           ,[CA_Brut_TTC]
--           ,[CA_BRut_TVA]
--           ,[CA_Brut_HT]
--           ,[Burst_CA_Brut_TTC]
--           ,[Burst_CA_Brut_TVA]
--           ,[Burst_CA_Brut_HT]
--           ,[Disc_Count]
--           ,[Disc_TTC]
--           ,[Disc_TVA]
--           ,[Disc_HT]
--           ,[Burst_Disc_TTC]
--           ,[Burst_Disc_TVA]
--           ,[Burst_Disc_HT]
--           ,[BPub_Count]
--           ,[Bpub_TTC]
--           ,[Bpub_TVA]
--           ,[Bpub_HT]
--           ,[BRepas_Count]
--           ,[BRepas_TTC]
--           ,[BRepas_TVA]
--           ,[BRepas_HT]
--           ,[VA_TTC]
--           ,[VA_TVA]
--           ,[VA_HT]
--           ,[CA_Net_TTC]
--           ,[CA_Net_TVA]
--           ,[CA_Net_HT]
--           ,[Burst_CA_Net_TTC]
--           ,[Burst_CA_Net_TVA]
--           ,[Burst_CA_Net_HT]
--           ,[Foodcost]
--           ,[IsMainCombo]
--           ,[TI_IsVoidReopenCheck]
--           ,[TI_OrderDateTime]
--           ,[TI_SendDate]
--           ,[TI_PrintDate]
--           ,[TI_KitchenDate]
--           ,[TI_TotalSales]
--           ,[TI_ReferenceInvoiceID]
--           ,[DWH_Process]
--           ,[DT_INS]
--           ,[DT_MAJ]
--           ,[DT_SUP]
--           ,[SOURCE]
--           ,[FLAG_DAY_CLOSING]
--           ,[Description])
SELECT 
[RestaurantCode]
           ,[RestaurantUniqueID]
           ,[InvoiceID]
           ,[InvoiceTransactionID]
           ,[CommercialDate]
           ,[CodePLU]
           ,[RevenueDate]
           ,[TITT_TaxeID]
           ,[Pays_seq]
           ,[CommercialMonth]
           ,[TI_OpenDate]
           ,[TI_CloseDate]
           ,[Periode]
           ,[CAT_RevenueCenterID]
           ,[InvoiceNumber]
           ,[FlagDeleted]
           ,[FlagPosted]
           ,[FlagTraining]
           ,[SID_PRODUCT]
           ,[ParentInvoiceTransactionID]
           ,[InCombo]
           ,[Quantity]
           ,[UnitPrice]
           ,[CA_Brut_TTC]
           ,[CA_BRut_TVA]
           ,[CA_Brut_HT]
           ,[Burst_CA_Brut_TTC]
           ,[Burst_CA_Brut_TVA]
           ,[Burst_CA_Brut_HT]
           ,[Disc_Count]
           ,[Disc_TTC]
           ,[Disc_TVA]
           ,[Disc_HT]
           ,[Burst_Disc_TTC]
           ,[Burst_Disc_TVA]
           ,[Burst_Disc_HT]
           ,[BPub_Count]
           ,[Bpub_TTC]
           ,[Bpub_TVA]
           ,[Bpub_HT]
           ,[BRepas_Count]
           ,[BRepas_TTC]
           ,[BRepas_TVA]
           ,[BRepas_HT]
           ,[VA_TTC]
           ,[VA_TVA]
           ,[VA_HT]
           ,[CA_Net_TTC]
           ,[CA_Net_TVA]
           ,[CA_Net_HT]
           ,[Burst_CA_Net_TTC]
           ,[Burst_CA_Net_TVA]
           ,[Burst_CA_Net_HT]
           ,[Foodcost]
           ,[IsMainCombo]
           ,[TI_IsVoidReopenCheck]
           ,[TI_OrderDateTime]
           ,[TI_SendDate]
           ,[TI_PrintDate]
           ,[TI_KitchenDate]
           ,[TI_TotalSales]
           ,[TI_ReferenceInvoiceID]
           ,[DWH_Process]
           ,[DT_INS]
           ,[DT_MAJ]
           ,[DT_SUP]
           ,[SOURCE]
           ,[FLAG_DAY_CLOSING]
           ,[Description]
FROM SID_PRD.ODS.[TICKET_UNIFIE]
where commercialdate = '20190301'
and RestaurantUniqueID =@restau
order by RestaurantUniqueID

   END;  
CLOSE Rest_Cursor;  
DEALLOCATE Rest_Cursor;  
GO  