USE [master]
GO

/****** Object:  Login [NEOFED\GU-SQL-NEOCLES]    Script Date: 06/05/2021 09:29:26 ******/
CREATE LOGIN [NEOFED\GU-SQL-NEOCLES] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [NEOFED\GU-SQL-NEOCLES]
GO


