USE [master]
GO
ALTER DATABASE [SID_PRD] SET PAGE_VERIFY NONE  WITH NO_WAIT
GO

ALTER DATABASE SID_DEV SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DBCC CheckDB ('SID_DEV', REPAIR_ALLOW_DATA_LOSS)

ALTER DATABASE SID_DEV SET MULTI_USER

USE [master]
GO
ALTER DATABASE [SID_PRD] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT
GO