SELECT P.ID_UNIQUE_RESTAURANT
, SUM(P.TOT)
FROM
(
	SELECT ID_UNIQUE_RESTAURANT
	, SID_REVENUE_CENTER
	, SUM(REVENUE_HT_NONREECLATE) AS [TOT]
	FROM DWH_COM..F_PRODUCT
	WHERE SID_DATE = '2015-06-10'
	AND ID_UNIQUE_RESTAURANT = 10010767
	GROUP BY SID_REVENUE_CENTER, ID_UNIQUE_RESTAURANT
) AS P
GROUP BY ID_UNIQUE_RESTAURANT
ORDER BY ID_UNIQUE_RESTAURANT

-----------------------------------------

SELECT ID_UNIQUE_RESTAURANT
, SUM(P.TOT_REVENUE_HT_RESTAURANT)
FROM
(
	SELECT DISTINCT ID_UNIQUE_RESTAURANT
	, SID_REVENUE_CENTER
	, TOT_REVENUE_HT_RESTAURANT
	FROM DWH_COM..F_PRODUCT
	WHERE SID_DATE = '2015-06-10'
	AND ID_UNIQUE_RESTAURANT = 10010767
) AS P
GROUP BY ID_UNIQUE_RESTAURANT
ORDER BY ID_UNIQUE_RESTAURANT